[tool.poetry]
name = "ragplus2buddy"
version = "0.3.0"
description = "Agentic RAG with sequential multi-agent pipeline"
authors = ["Seer Neil <seerneil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
streamlit = "^1.39.0"
requests = "^2.32.0"
pymupdf = "^1.24.0"
scikit-learn = "^1.5.0"
pandas = "^2.1.0"
rpds-py = "^0.30"
langchain-core = "^0.3.0"
langgraph = "^0.2.0"
tavily-python = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
